nameOverride: "{{ .Values.GIT_REPO }}"

livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http

resources:
  requests:
    cpu: 100m
    memory: 100Mi

  # limits:
  #   cpu: 200m
  #   memory: 500Mi

volumeMounts:
  - name: tmp-dir
    mountPath: /tmp

sidecars: {}

initContainers: {}

volumes:
  - name: tmp-dir
    emptyDir: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

ingress:
  enabled: true
  tlsEnabled: true
  servicePort: 8080
  tlsSecretName: "{{ .Values.CI_TLS_SECRET_NAME}}"
  ingressClassName: nginx
